const DEFAULT_ROOMS_DATA = [
    {
        id: "room-001",
        title: "Modern Studio in BKK1",
        location: "Boeung Keng Kang 1, Phnom Penh, Cambodia",
        price: 85,
        description: "A stylish and modern studio apartment located in the popular BKK1 district. Ideal for singles or couples. Features a compact kitchen, private bathroom, and balcony. Close to cafes, restaurants, and international schools.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9HQSg0TYoumuo7gRz985wusb3BTeRimUahQ&s",
        amenities: ["Wi-Fi", "Furnished", "Balcony", "Near Restaurants"],
        ownerId: "seed-user-1",
        contactPhone: "+85512345678",
        contactEmail: "bkk1.studio@example.com",
        isAvailable: true // Added isAvailable status
    },
    {
        id: "room-002",
        title: "Spacious 2-Bedroom in Tonle Basak",
        location: "Tonle Basak, Phnom Penh, Cambodia",
        price: 150,
        description: "Generous 2-bedroom apartment with a bright living area, modern kitchen, and river views. Perfect for families, with easy access to Aeon Mall and embassy row.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrDr9gVzT83OZx_PctTKmj_SAC_HsLj6-LuQ&s",
        amenities: ["River View", "Parking", "2 Bathrooms", "Dishwasher"],
        ownerId: "seed-user-2",
        contactPhone: "+85598765432",
        contactEmail: "tonlebasak.flat@example.com",
        isAvailable: false // Added isAvailable status
    },
    {
        id: "room-003",
        title: "Loft Apartment in Daun Penh",
        location: "Daun Penh, Phnom Penh, Cambodia",
        price: 120,
        description: "Unique loft apartment with high ceilings and exposed brick walls, located in the vibrant Daun Penh area. Close to the Royal Palace and Riverside. Ideal for creatives.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR04It5aM540rdjR6N0HrZap5986tsSWrgguw&s",
        amenities: ["High Ceilings", "City Center", "Laundry In-Unit", "Walkable"],
        ownerId: "seed-user-1",
        contactPhone: "+85577123456",
        contactEmail: "daunpenh.loft@example.com",
        isAvailable: true // Added isAvailable status
    },
    {
        id: "room-004",
        title: "Cozy Room near Royal University",
        location: "Russian Market Area, Phnom Penh, Cambodia",
        price: 50,
        description: "Affordable and cozy room, perfect for students attending nearby universities. Shared bathroom and kitchen facilities. Quiet residential street.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9HQSg0TYoumuo7gRz985wusb3BTeRimUahQ&s",
        amenities: ["Shared Bathroom", "Shared Kitchen", "Study Desk", "Close to University"],
        ownerId: "seed-user-3",
        contactPhone: "+85588999000",
        contactEmail: "student.room@example.com",
        isAvailable: true // Added isAvailable status
    },
    {
        id: "room-005",
        title: "Luxury Penthouse with Rooftop Pool",
        location: "Koh Pich, Phnom Penh, Cambodia",
        price: 45,
        description: "Exclusive penthouse living on Diamond Island. Features stunning panoramic city and river views, private rooftop pool, and high-end finishes. Ultimate luxury.",
        image: "https://tbn0.gstatic.com/images?q=tbn:ANd9GcT14tHDGziDIoDgvuXne2_pjZ_gVJmKkOjo5w&s",
        amenities: ["Private Pool", "City Views", "Gourmet Kitchen", "24/7 Concierge"],
        ownerId: "seed-user-5",
        contactPhone: "+85569112233",
        contactEmail: "kohpich.penthouse@example.com",
        isAvailable: false // Added isAvailable status
    },
    {
        id: "room-006",
        title: "Family Villa with Garden",
        location: "Sen Sok, Phnom Penh, Cambodia",
        price: 200,
        description: "Spacious villa with a large private garden, ideal for families. Three bedrooms, modern bathrooms, and secure parking. Located in a tranquil residential area.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-nrmtJa8qDiBFoA_xcN5dFZutx4_3Ih9u7Q&s",
        amenities: ["Private Garden", "Parking", "Kid-Friendly", "Pet-Friendly"],
        ownerId: "seed-user-2",
        contactPhone: "+85578555666",
        contactEmail: "sensok.villa@example.com",
        isAvailable: true // Added isAvailable status
    },
    {
        id: "room-007",
        title: "Compact 1-Bedroom in Chamkarmon",
        location: "Chamkarmon, Phnom Penh, Cambodia",
        price: 70,
        description: "Efficient and well-designed 1-bedroom apartment, perfect for individuals. Modern finishes and a convenient location close to local amenities.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQz58hJF7uhvdd_4TBsSoiwyrInLHB5hFz9hw&s",
        amenities: ["Furnished", "Modern Finishes", "Near Shops", "Air Conditioning"],
        ownerId: "seed-user-1",
        contactPhone: "+85596333444",
        contactEmail: "chamkarmon.apt@example.com",
        isAvailable: true // Added isAvailable status
    },
    {
        id: "room-008",
        title: "Riverside 3-Bedroom Apartment",
        location: "Riverside, Phnom Penh, Cambodia",
        price: 200,
        description: "Stunning 3-bedroom apartment overlooking the Mekong River. Spacious living area, large balcony, and breathtaking sunset views. Walk to FCC and night market.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqktRNM_9_XxJBDb6pvCxqi7awgjdryNf7og&s",
        amenities: ["River View", "Balcony", "Fully Furnished", "Near Nightlife"],
        ownerId: "seed-user-6",
        contactPhone: "+85517888777",
        contactEmail: "riverside.view@example.com",
        isAvailable: false // Added isAvailable status
    },
    {
        id: "room-009",
        title: "Shared Student Accommodation",
        location: "Tuol Kork, Phnom Penh, Cambodia",
        price: 30,
        description: "Affordable shared room in a friendly student complex. Access to communal study areas, kitchen, and recreation room. Ideal for budget-conscious students.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTADRqTvwvOzOsEdTo3loLvqMivoZ9IcSiVDQ&s",
        amenities: ["All Utilities", "Communal Kitchen", "Study Area", "Near Campus"],
        ownerId: "seed-user-7",
        contactPhone: "+85510223344",
        contactEmail: "tuolkork.student@example.com",
        isAvailable: true // Added isAvailable status
    },
    {
        id: "room-010",
        title: "Serviced Apartment with Gym & Pool",
        location: "BKK3, Phnom Penh, Cambodia",
        price: 50,
        description: "Comfortable serviced apartment offering residents a well-equipped gym and refreshing swimming pool. Includes weekly cleaning and secure parking. Great for expats.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKPtQTL39NO6QR7w9Q14YIbByAGDhcoGgEzg&s",
        amenities: ["Gym Access", "Swimming Pool", "Serviced", "Parking"],
        ownerId: "seed-user-8",
        contactPhone: "+85518777666",
        contactEmail: "bkk3.serviced@example.com",
        isAvailable: true // Added isAvailable status
    },
    {
        id: "room-011",
        title: "Boutique Apartment near Central Market",
        location: "Daun Penh, Phnom Penh, Cambodia",
        price: 110,
        description: "Charming boutique apartment with unique Khmer-inspired decor, just a short walk from Central Market. Offers a blend of traditional style and modern comfort.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4SUUdmOTjiq7THGKHca8DVK1AfdRnDzbxvA&s",
        amenities: ["Unique Decor", "Near Market", "Furnished", "Air Conditioning"],
        ownerId: "seed-user-9",
        contactPhone: "+85599555444",
        contactEmail: "boutique.daunpenh@example.com",
        isAvailable: false // Added isAvailable status
    },
    {
        id: "room-012",
        title: "Modern 1-Bedroom in Toul Tum Poung",
        location: "Toul Tum Poung, Phnom Penh, Cambodia",
        price: 80,
        description: "A sleek 1-bedroom apartment in the vibrant Russian Market area. Popular with expats, offering a comfortable living space and easy access to local eateries and shops.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDLA6A-EwVn_k4d0rYi6vB4dWiRYGO_zuKwQ&s",
        amenities: ["Modern Kitchen", "Balcony", "Near Russian Market", "Utilities Excluded"],
        ownerId: "seed-user-10",
        contactPhone: "+85512333222",
        contactEmail: "toul.tumpoung@example.com",
        isAvailable: true // Added isAvailable status
    },
    {
        id: "room-013",
        title: "Large Family Home in Chroy Changvar",
        location: "Chroy Changvar, Phnom Penh, Cambodia",
        price: 250,
        description: "Spacious family home on the peninsula, offering ample living space and proximity to new developments. Features multiple bedrooms and a private yard.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDpV2Owh6Sizau4xtMR9G9lhK9OHT7le9uSQ&s",
        amenities: ["Large Yard", "Multiple Bedrooms", "Quiet Area", "Parking"],
        ownerId: "seed-user-11",
        contactPhone: "+85577888999",
        contactEmail: "chroy.family@example.com",
        isAvailable: true // Added isAvailable status
    },
    {
        id: "room-014",
        title: "Executive Studio near Independence Monument",
        location: "Boeung Keng Kang 2, Phnom Penh, Cambodia",
        price: 90,
        description: "High-quality executive studio ideal for professionals. Located strategically near the Independence Monument, offering convenience and a prestigious address.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR04It5aM540rdjR6N0HrZap5986tsSWrgguw&s",
        amenities: ["Prime Location", "Furnished", "Secure Building", "Close to Amenities"],
        ownerId: "seed-user-1",
        contactPhone: "+85512345678",
        contactEmail: "bkk2.exec@example.com",
        isAvailable: false // Added isAvailable status
    },
    {
        id: "room-015",
        title: "Affordable Room near Russian Hospital",
        location: "Boeung Trabek, Phnom Penh, Cambodia",
        price: 300,
        description: "Budget-friendly single room in a convenient location, close to the Russian Hospital. Ideal for medical students or those working in the area.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3tlHN_meBJInYYn1MJNSH8q3xxBs2iaTDnQ&s",
        amenities: ["Affordable", "Basic Furnishings", "Near Hospital", "Quiet Street"],
        ownerId: "seed-user-4",
        contactPhone: "+85597666555",
        contactEmail: "russian.hospital@example.com",
        isAvailable: true // Added isAvailable status
    },
    {
        id: "room-016",
        title: "Modern Condo in Koh Norea",
        location: "Koh Norea, Phnom Penh, Cambodia",
        price: 180,
        description: "Brand new modern condominium unit with river views. Located in a developing area, promising a new urban lifestyle. Building includes shared facilities.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBCBTIKZ6TpUoxaQIWuQ9JqFnDpiv9p9Xobg&s",
        amenities: ["New Development", "River View", "Shared Gym", "Shared Pool"],
        ownerId: "seed-user-12",
        contactPhone: "+85586444333",
        contactEmail: "kohnorea.condo@example.com",
        isAvailable: true // Added isAvailable status
    },
    {
        id: "room-017",
        title: "Traditional Khmer House for Rent",
        location: "Mean Chey, Phnom Penh, Cambodia",
        price: 100,
        description: "Experience authentic Cambodian living in this traditional wooden house. Features spacious rooms and a private yard. Perfect for cultural immersion.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQTC-Ui5vddjQqKQGIkLgx71D03CgMgls-LA&s",
        amenities: ["Traditional Style", "Private Yard", "Unfurnished", "Authentic Experience"],
        ownerId: "seed-user-13",
        contactPhone: "+85515999888",
        contactEmail: "khmer.house@example.com",
        isAvailable: false // Added isAvailable status
    },
    {
        id: "room-018",
        title: "Serviced Studio in Toul Svay Prey",
        location: "Toul Svay Prey 1, Phnom Penh, Cambodia",
        price: 65,
        description: "Convenient serviced studio apartment with regular cleaning. Fully furnished and ready to move in. Close to local markets and commercial areas.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdlVzG9JupJOBg_zo_XowVJm3hMOh3hYbChg&s",
        amenities: ["Serviced", "Fully Furnished", "Cleaning Service", "Near Markets"],
        ownerId: "seed-user-14",
        contactPhone: "+85593112233",
        contactEmail: "tsp.studio@example.com",
        isAvailable: true // Added isAvailable status
    },
    {
        id: "room-019",
        title: "High-Floor 1-Bedroom with Cityscape",
        location: "7 Makara, Phnom Penh, Cambodia",
        price: 130,
        description: "Enjoy stunning cityscape views from this high-floor 1-bedroom apartment. Modern design and access to building amenities. Located in a central and vibrant district.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmx1nEgvSjsJPQgzmqeD0YXWgnePblOd0Y1Q&s",
        amenities: ["Cityscape Views", "High Floor", "Gym Access", "Central Location"],
        ownerId: "seed-user-15",
        contactPhone: "+85516777888",
        contactEmail: "7makara.apt@example.com",
        isAvailable: true // Added isAvailable status
    },
    {
        id: "room-020",
        title: "New Development Apartment",
        location: "Boeung Kak 2, Phnom Penh, Cambodia",
        price: 90,
        description: "Brand new apartment in a rapidly developing area. Modern amenities and fresh interiors. Be one of the first to live in this exciting new complex.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSya64dX2Vr2SyrCBuxqFKTGUkHWHkn7lLDQ&s",
        amenities: ["New Building", "Modern Amenities", "Spacious", "Developing Area"],
        ownerId: "seed-user-16",
        contactPhone: "+85511555444",
        contactEmail: "boeng.kak2@example.com",
        isAvailable: false // Added isAvailable status
    },
    {
        id: "room-021",
        title: "Quiet Room in Toul Svay Prey 2",
        location: "Toul Svay Prey 2, Phnom Penh, Cambodia",
        price: 100,
        description: "A tranquil single room situated in a peaceful part of Toul Svay Prey. Ideal for those seeking quiet living while remaining close to the city's conveniences.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8YqH5gBmb7-uY4aFFBiqCZRVOHIqEcDB1LA&s",
        amenities: ["Quiet Location", "Shared Bathroom", "Basic Furnishings", "Near Local Shops"],
        ownerId: "seed-user-17",
        contactPhone: "+85567888999",
        contactEmail: "tsp2.room@example.com",
        isAvailable: true // Added isAvailable status
    },
    {
        id: "room-022",
        title: "Family Apartment with Balcony",
        location: "Prampir Meakkakra, Phnom Penh, Cambodia",
        price: 60,
        description: "Comfortable family apartment with a spacious living room and a lovely balcony. Located in a central district, offering easy access to schools and markets.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1xroON2ZO6XrVU58Dm00wEclhK_KiiNxyZQ&s",
        amenities: ["Balcony", "Family-Friendly", "Near Schools", "Furnished Options"],
        ownerId: "seed-user-2",
        contactPhone: "+85598765432",
        contactEmail: "prampir.family@example.com",
        isAvailable: true // Added isAvailable status
    },
    {
        id: "room-023",
        title: "Expansive Luxury Residence",
        location: "Russey Keo, Phnom Penh, Cambodia",
        price: 80,
        description: "An expansive luxury residence offering multiple bedrooms, large living areas, and high-end amenities. Perfect for a large family or those desiring ultimate space.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR94OPb5xXdxTheXPYG8VAF2e4MDEzruIMuag&s",
        amenities: ["Multiple Bedrooms", "High-End", "Spacious", "Gated Community (possible)"],
        ownerId: "seed-user-5",
        contactPhone: "+85569112233",
        contactEmail: "russey.luxury@example.com",
        isAvailable: false // Added isAvailable status
    },
    {
        id: "room-024",
        title: "Co-working Studio Space",
        location: "Chamkarmon, Phnom Penh, Cambodia",
        price: 75,
        description: "A modern studio apartment designed for productivity, featuring a dedicated co-working space. Ideal for digital nomads or those working from home.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqj6ZGNept9sQ0p_3OKVA7nuRqAILIQndtxw&s",
        amenities: ["Co-working Area", "High-Speed Wi-Fi", "Furnished", "Quiet Building"],
        ownerId: "seed-user-1",
        contactPhone: "+85577123456",
        contactEmail: "cowork.studio@example.com",
        isAvailable: true // Added isAvailable status
    },
    {
        id: "room-025",
        title: "Garden View Apartment in BKK1",
        location: "Boeung Keng Kang 1, Phnom Penh, Cambodia",
        price: 100,
        description: "Beautiful 1-bedroom apartment with a serene garden view, located in the prestigious BKK1 area. Offers a peaceful escape in the heart of the city.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTN5mytrfdVwbdIqSRr1EN453AzRPZp00lEA&s",
        amenities: ["Garden View", "Peaceful", "Furnished", "Central Location"],
        ownerId: "seed-user-10",
        contactPhone: "+85512333222",
        contactEmail: "bkk1.garden@example.com",
        isAvailable: true // Added isAvailable status
    }
];

window.DEFAULT_ROOMS_DATA = DEFAULT_ROOMS_DATA;